/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package pkgVista;

import java.util.Calendar;
import javax.swing.JOptionPane;
import static pkgVista.frmRegistro.txtresibo;

/**
 *
 * @author Edierlargo
 */
public class frmMenu extends javax.swing.JFrame {

    /**
     * Creates new form frmMenu
     */
    public frmMenu() {
        initComponents();
        setLocationRelativeTo(null);
        
       java.util.Date fechaActual = new java.util.Date();
        java.text.SimpleDateFormat formato = new java.text.SimpleDateFormat("dd-MM-yyyy");
        lblfecha.setText(formato.format(fechaActual));
        Calendar cal1 = Calendar.getInstance();
        txthora.setText(""+cal1.get(Calendar.HOUR)+":"+cal1.get(Calendar.MINUTE)+":"+cal1.get(Calendar.SECOND));
    }
    public void ingresartermino(){
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jblinformacion = new javax.swing.JLabel();
        lblhora = new javax.swing.JLabel();
        txthora = new javax.swing.JTextField();
        lblfecha1 = new javax.swing.JLabel();
        lblfecha = new javax.swing.JLabel();
        lbltrabajando = new javax.swing.JLabel();
        txtresibotrabajador = new javax.swing.JTextField();
        jToolBar1 = new javax.swing.JToolBar();
        btnPersona = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        btnsolicitudes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MENU");

        jblinformacion.setFont(new java.awt.Font("Adobe Garamond Pro", 1, 36)); // NOI18N
        jblinformacion.setText("BIBLIOTECA ");

        lblhora.setText("HORA");

        txthora.setEnabled(false);
        txthora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txthoraActionPerformed(evt);
            }
        });

        lblfecha1.setText("FECHA");

        lbltrabajando.setText("TRABAJANDO");

        txtresibotrabajador.setEnabled(false);
        txtresibotrabajador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtresibotrabajadorActionPerformed(evt);
            }
        });

        jToolBar1.setRollover(true);

        btnPersona.setIcon(new javax.swing.ImageIcon("C:\\Users\\Edierlargo\\Music\\Iconos\\1432544022_books.png")); // NOI18N
        btnPersona.setText("PRESTAMOS");
        btnPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPersonaActionPerformed(evt);
            }
        });
        jToolBar1.add(btnPersona);

        btnCerrar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Edierlargo\\Music\\Iconos\\1432544588_home.png")); // NOI18N
        btnCerrar.setText(" INICIO");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnCerrar);

        btnsolicitudes.setIcon(new javax.swing.ImageIcon("C:\\Users\\Edierlargo\\Music\\Iconos\\PRESTARLIBRO.png")); // NOI18N
        btnsolicitudes.setText("DEVOLUCIONES");
        btnsolicitudes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsolicitudesActionPerformed(evt);
            }
        });
        jToolBar1.add(btnsolicitudes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbltrabajando)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtresibotrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblhora)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txthora, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(lblfecha1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblfecha, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 107, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jblinformacion, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jblinformacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblfecha1)
                    .addComponent(lblfecha, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblhora)
                    .addComponent(txthora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbltrabajando)
                    .addComponent(txtresibotrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        // TODO add your handling code here:
        
         frmRegistro abrir=new frmRegistro();
        abrir.setVisible(true);
        frmRegistro.txtresibo.setText(txthora.getText());
       ingresartermino();
        pkgModelo.clsDAORegistro obj;
        obj=new pkgModelo.clsDAORegistro();
        obj.setHoratermino(txthora.getText());
           this.dispose();
        
        
        
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPersonaActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPersona().setVisible(true);
            }
        });
        this.dispose();
    }//GEN-LAST:event_btnPersonaActionPerformed

    private void btnsolicitudesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsolicitudesActionPerformed
        // TODO add your handling code here:
        pkgModelo.clsDAOPersona obj;
        obj=new pkgModelo.clsDAOPersona();
        String de=JOptionPane.showInputDialog("INGRESE NUMERO DE CEDULA");
        obj.setId(de);
        if (de.isEmpty()){
            JOptionPane.showMessageDialog(null, "INGRESE CODIGO", "ERROR", JOptionPane.ERROR_MESSAGE);
            
        }
        else{
         
          
         java.util.ArrayList resu = new java.util.ArrayList();
         resu=obj.consultar();
         if (resu.size() == 0){
            JOptionPane.showMessageDialog(null, "NO EXISTE ! NO HA PRESTADO LIBROS");
         }else{
            jfrdevoluciones abrir=new jfrdevoluciones();
         abrir.setVisible(true);
         this.dispose();
            jfrdevoluciones.resibonombre.setText(resu.get(0).toString());
             jfrdevoluciones.txtresiboReferencia.setText(resu.get(1).toString());
            jfrdevoluciones.resibonombrelibro.setText(resu.get(2).toString());
            jfrdevoluciones.txtresiboId.setText(de);
            
        }
        
        }
        
         
        
      
        
    }//GEN-LAST:event_btnsolicitudesActionPerformed

    private void txthoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txthoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txthoraActionPerformed

    private void txtresibotrabajadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtresibotrabajadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtresibotrabajadorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnPersona;
    private javax.swing.JButton btnsolicitudes;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel jblinformacion;
    private javax.swing.JLabel lblfecha;
    private javax.swing.JLabel lblfecha1;
    private javax.swing.JLabel lblhora;
    private javax.swing.JLabel lbltrabajando;
    public static javax.swing.JTextField txthora;
    public static javax.swing.JTextField txtresibotrabajador;
    // End of variables declaration//GEN-END:variables
}
