/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package pkgVista;

import javax.swing.JOptionPane;

/**
 *
 * @author Edierlargo
 */
public class frmPersona extends javax.swing.JFrame {

    /**
     * Creates new form frmPersona
     */
    public frmPersona() {
        initComponents();
        setLocationRelativeTo(null);
        listar();
         java.util.Date fechaActual = new java.util.Date();
        java.text.SimpleDateFormat formato = new java.text.SimpleDateFormat("dd-MM-yyyy");
        lblfecha.setText(formato.format(fechaActual));
    }
    public void borrar(){
        txtId.setText("");
        txtNombre.setText("");
        txtNombrelibro.setText("");
        txtReferencia.setText("");
    }
    
    public void listar(){
        pkgModelo.clsDAOPersona obj;
        obj=new pkgModelo.clsDAOPersona();
        tblInfo.setModel(obj.listar(tblInfo));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bar = new javax.swing.JToolBar();
        btnAgregarListar = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        lblId = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblInfo = new javax.swing.JTable();
        lblreferencia = new javax.swing.JLabel();
        txtReferencia = new javax.swing.JTextField();
        txtNombrelibro = new javax.swing.JTextField();
        lblNombrelibro = new javax.swing.JLabel();
        lblfecha = new javax.swing.JLabel();
        lblfecha1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PRESTAMO DE LIBROS");

        bar.setRollover(true);

        btnAgregarListar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Edierlargo\\Music\\Iconos\\PRESTARLIBRO.png")); // NOI18N
        btnAgregarListar.setText("PRESTAR LIBRO");
        btnAgregarListar.setToolTipText("Agrega y lista personas");
        btnAgregarListar.setFocusable(false);
        btnAgregarListar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAgregarListar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAgregarListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarListarActionPerformed(evt);
            }
        });
        bar.add(btnAgregarListar);

        btnConsultar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Edierlargo\\Music\\Iconos\\1432543223_search_b.png")); // NOI18N
        btnConsultar.setText("CONSULTAR");
        btnConsultar.setFocusable(false);
        btnConsultar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnConsultar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });
        bar.add(btnConsultar);

        btnBorrar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Edierlargo\\Music\\Iconos\\1432544990_edit-delete.png")); // NOI18N
        btnBorrar.setText("BORRAR");
        btnBorrar.setFocusable(false);
        btnBorrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBorrar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });
        bar.add(btnBorrar);

        btnModificar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Edierlargo\\Music\\Iconos\\modificar.png")); // NOI18N
        btnModificar.setText("MODIFICAR");
        btnModificar.setFocusable(false);
        btnModificar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnModificar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        bar.add(btnModificar);

        btnCerrar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Edierlargo\\Music\\Iconos\\1432541838_Exit.png")); // NOI18N
        btnCerrar.setText("CERRAR");
        btnCerrar.setFocusable(false);
        btnCerrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCerrar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        bar.add(btnCerrar);

        lblId.setText("CODIGO  ESTUDIANTE");

        lblNombre.setText("NOMBRE DEL ESTUDIANTE");

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        tblInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CODIGO", "NOMBRE", "REFERENCIA", "NOMBRE DEL LIBRO", "FECHA"
            }
        ));
        jScrollPane1.setViewportView(tblInfo);

        lblreferencia.setText("REFERENCIA DEL LIBRO");

        txtNombrelibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombrelibroActionPerformed(evt);
            }
        });

        lblNombrelibro.setText("NOMBRE DEL LIBRO");

        lblfecha1.setText("FECHA");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblId)
                                    .addComponent(lblNombre)
                                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNombrelibro, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtReferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblNombrelibro))
                                        .addGap(18, 18, 18)
                                        .addComponent(lblfecha1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblfecha, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lblreferencia)))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 932, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bar, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblId)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblfecha1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblNombrelibro))
                        .addComponent(lblfecha, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtReferencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(lblNombre))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblreferencia)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombrelibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void btnAgregarListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarListarActionPerformed
        // TODO add your handling code here:
        if (txtId.getText().isEmpty()&&txtNombre.getText().isEmpty()&&txtNombrelibro.getText().isEmpty()&&txtReferencia.getText().isEmpty()){
            
            JOptionPane.showMessageDialog(null, "CAMPOS VACIOS", "ERROR", JOptionPane.ERROR_MESSAGE);   
        }else{
            if (txtId.getText().isEmpty()){
            
            JOptionPane.showMessageDialog(null, "INGRESE CODIGO", "ERROR", JOptionPane.ERROR_MESSAGE);   
        }else{
              if (txtNombre.getText().isEmpty()){
            
            JOptionPane.showMessageDialog(null, "INGRESE NOMBRE", "ERROR", JOptionPane.ERROR_MESSAGE);   
        }else{
                    if (txtReferencia.getText().isEmpty()){
            
            JOptionPane.showMessageDialog(null, "INGRESE LA REFERENCIA DEL LIBRO", "ERROR", JOptionPane.ERROR_MESSAGE);   
        }else{
                          if (txtNombrelibro.getText().isEmpty()){
            
            JOptionPane.showMessageDialog(null, "INGRESE NOMBRE DEL LIBRO", "ERROR", JOptionPane.ERROR_MESSAGE);   
        }else{
        pkgModelo.clsDAOPersona obj;
        obj=new pkgModelo.clsDAOPersona();
        obj.setId(txtId.getText());
        obj.setNombre(txtNombre.getText());
        obj.setRef(txtReferencia.getText());
        obj.setNomlibro(txtNombrelibro.getText());
        obj.setFecha(lblfecha.getText());
        
        if (obj.insertar() == true){
            JOptionPane.showMessageDialog(rootPane, "NO SE PUDO PRESTAR");
            
        }
        else{
            JOptionPane.showMessageDialog(rootPane, " PRESTADO");
            listar();
            borrar();
        }
            }
                    }
              }
            }
        }
        
    }//GEN-LAST:event_btnAgregarListarActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        // TODO add your handling code here:
        
         java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMenu().setVisible(true);
            }
        });
         this.dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        // TODO add your handling code here:
       
        pkgModelo.clsDAOPersona obj;
        obj=new pkgModelo.clsDAOPersona();
        String de=JOptionPane.showInputDialog("INGRESE EL ODDIGO DE ESTUDIANTE");
        //txtId.setText(de); este metodo tambien sirve par buscar por cedula
         obj.setId(de);
         if (de.isEmpty()){
            JOptionPane.showMessageDialog(null, "INGRESE CODIGO", "ERROR", JOptionPane.ERROR_MESSAGE);
            
        }else{
         
         java.util.ArrayList resu = new java.util.ArrayList();
         resu=obj.consultar();
         if (resu.size() == 0){
            JOptionPane.showMessageDialog(null, "NO EXISTE");
         }else{
             
            txtNombre.setText(resu.get(0).toString());
             txtNombrelibro.setText(resu.get(1).toString());
            txtReferencia.setText(resu.get(2).toString());
            txtId.setText(de);
        }
         }
        
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        // TO add your handling code here:
        pkgModelo.clsDAOPersona obj;
        obj=new pkgModelo.clsDAOPersona();
        int fila=tblInfo.getSelectedRow();
        if (fila != -1){
            String codigo=tblInfo.getValueAt(fila, 0).toString();
            obj.setId(codigo);
            obj.borrar();
            listar();
        }
        else{

            JOptionPane.showMessageDialog(null, "SELECCIONE UNA COLUMNA PARA BORRAR", "ERROR", JOptionPane.ERROR_MESSAGE);
            
     }
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
        
        pkgModelo.clsDAOPersona obj;
        String de=JOptionPane.showInputDialog("INGRESE CODIGO");
        obj=new pkgModelo.clsDAOPersona();
        obj.setId(de);
        if (de.isEmpty()){
            JOptionPane.showMessageDialog(null, "INGRESE CODIGO", "ERROR", JOptionPane.ERROR_MESSAGE);
            
        }else{
        obj.setNombre(txtNombre.getText());
        obj.setRef(txtReferencia.getText());
        obj.setNomlibro(txtNombrelibro.getText());
        if(obj.modificar() == false){
         listar();
            JOptionPane.showMessageDialog(rootPane, "Se modificó");
            borrar();
        }
        else{
            JOptionPane.showMessageDialog(rootPane, "No Se modificó");
        }
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void txtNombrelibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombrelibroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombrelibroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPersona().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToolBar bar;
    private javax.swing.JButton btnAgregarListar;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNombrelibro;
    private javax.swing.JLabel lblfecha;
    private javax.swing.JLabel lblfecha1;
    private javax.swing.JLabel lblreferencia;
    private javax.swing.JTable tblInfo;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombrelibro;
    private javax.swing.JTextField txtReferencia;
    // End of variables declaration//GEN-END:variables
}
