/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package pkgVista;

import java.util.Calendar;
import javax.swing.JOptionPane;

/**
 *
 * @author Edierlargo
 */
public class jfrdevoluciones extends javax.swing.JFrame {

    /**
     * Creates new form jfrdevoluciones
     */
    public jfrdevoluciones() {
        initComponents();
        setLocationRelativeTo(null);
        listar();
        java.util.Date fechaActual = new java.util.Date();
        java.text.SimpleDateFormat formato = new java.text.SimpleDateFormat("dd-MM-yyyy");
        lblfecha.setText(formato.format(fechaActual));
        
        // Se toma la hora y pone en la caja de texto
        Calendar cal1 = Calendar.getInstance();
        hora.setText(""+cal1.get(Calendar.HOUR)+":"+cal1.get(Calendar.MINUTE)+":"+cal1.get(Calendar.SECOND));
        
        
        
        
    }
     public void listar(){
        pkgModelo.clsDAOentregar obj;
        obj=new pkgModelo.clsDAOentregar();
        tableinfo.setModel(obj.listar(tableinfo));
    }
     public void entrega(){
         txtresiboId.setText("");
         txtresiboReferencia.setText("");
         resibonombre.setText("");
         resibonombrelibro.setText("");
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        resibonombre = new javax.swing.JTextField();
        lblreferencia = new javax.swing.JLabel();
        txtresiboReferencia = new javax.swing.JTextField();
        resibonombrelibro = new javax.swing.JTextField();
        lblNombrelibro = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        txtresiboId = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        jToolBar = new javax.swing.JToolBar();
        btnentregar = new javax.swing.JButton();
        btnconsultar = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        btnsalir = new javax.swing.JButton();
        lblinfo = new javax.swing.JLabel();
        lblfecha = new javax.swing.JLabel();
        lblhora = new javax.swing.JLabel();
        hora = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableinfo = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DEVOLUCIONES DE LIBROS");

        resibonombre.setEnabled(false);
        resibonombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resibonombreActionPerformed(evt);
            }
        });

        lblreferencia.setText("REFERENCIA DEL LIBRO");

        txtresiboReferencia.setEnabled(false);

        resibonombrelibro.setEnabled(false);
        resibonombrelibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resibonombrelibroActionPerformed(evt);
            }
        });

        lblNombrelibro.setText("NOMBRE DEL LIBRO");

        lblId.setText("CODIGO  ESTUDIANTE");

        txtresiboId.setEnabled(false);

        lblNombre.setText("NOMBRE DEL ESTUDIANTE");

        jToolBar.setRollover(true);

        btnentregar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Edierlargo\\Music\\Iconos\\devolver.png")); // NOI18N
        btnentregar.setText("ENTREGAR");
        btnentregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnentregarActionPerformed(evt);
            }
        });
        jToolBar.add(btnentregar);

        btnconsultar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Edierlargo\\Music\\Iconos\\1432543223_search_b.png")); // NOI18N
        btnconsultar.setText("CONSULTAR");
        btnconsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnconsultarActionPerformed(evt);
            }
        });
        jToolBar.add(btnconsultar);

        btneliminar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Edierlargo\\Music\\Iconos\\1432544990_edit-delete.png")); // NOI18N
        btneliminar.setText("ELIMINAR");
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });
        jToolBar.add(btneliminar);

        btnsalir.setIcon(new javax.swing.ImageIcon("C:\\Users\\Edierlargo\\Music\\Iconos\\1432541838_Exit.png")); // NOI18N
        btnsalir.setText("SALIR");
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });
        jToolBar.add(btnsalir);

        lblinfo.setText("FECHA");

        lblhora.setText("HORA");

        tableinfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                " CODIGO ESTUDIANTE", "NOMBRE ESTUDIANTE", "REFERENCIA LIBRO ", "NOMBRE DEL LIBRO", "FECHA", "ENTREGO", "HORA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableinfo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblNombre)
                            .addComponent(resibonombre)
                            .addComponent(txtresiboId, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblId))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(resibonombrelibro, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtresiboReferencia, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblNombrelibro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(lblreferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblinfo)
                            .addComponent(lblhora))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hora, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblfecha, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jToolBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 961, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jToolBar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblId)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtresiboId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblreferencia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtresiboReferencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(lblNombrelibro))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resibonombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resibonombrelibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblinfo)
                    .addComponent(lblfecha, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblhora)
                    .addComponent(hora, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void resibonombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resibonombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resibonombreActionPerformed

    private void resibonombrelibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resibonombrelibroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resibonombrelibroActionPerformed

    private void btnentregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnentregarActionPerformed
        // TODO add your handling code here:
        pkgModelo.clsDAOentregar obj;
        obj=new pkgModelo.clsDAOentregar();
        if (resibonombre.getText().isEmpty()&&txtresiboId.getText().isEmpty()&&txtresiboReferencia.getText().isEmpty()&&resibonombrelibro.getText().isEmpty()){
            
            JOptionPane.showMessageDialog(null, "CAMPOS VACIOS", "ERROR", JOptionPane.ERROR_MESSAGE);   
        }else{
        if(resibonombre.getText().isEmpty()) {
         JOptionPane.showMessageDialog(null, "INGRESE NOMBRE", "ERROR", JOptionPane.ERROR_MESSAGE);
          
              
          }else{
            if(txtresiboId.getText().isEmpty()) {
         JOptionPane.showMessageDialog(null, "INGRESE CODIGO", "ERROR", JOptionPane.ERROR_MESSAGE);
          
              
          }else{
                if(txtresiboReferencia.getText().isEmpty()) {
         JOptionPane.showMessageDialog(null, "INGRESE REFERENCIA DELLIBRO", "ERROR", JOptionPane.ERROR_MESSAGE);
          
              
          }else{
                    if(resibonombrelibro.getText().isEmpty()) {
         JOptionPane.showMessageDialog(null, "INGRESE NOMBRE DEL LIBRO", "ERROR", JOptionPane.ERROR_MESSAGE);
          
              
          }else{
        String devolvio;
        String nodevolvio;
        nodevolvio="NO";
        devolvio="SI";
        
        obj.setId(txtresiboId.getText());
        obj.setNombre(resibonombre.getText());
        obj.setRef(txtresiboReferencia.getText());
        obj.setNomlibro(resibonombrelibro.getText());
        obj.setFechaentrega(lblfecha.getText());
        obj.setHora(hora.getText());
        obj.setEntrego(devolvio);
        
        if (obj.insertar() == true){
            obj.setEntrego(nodevolvio);
            JOptionPane.showMessageDialog(rootPane, "NO SE DEVOLVIO *!");
                 
        }
        else{
            
            JOptionPane.showMessageDialog(rootPane, " GRACIAS POR DEVOLVER EL LIBRO !");
            
            listar();
            entrega();
        }
        }
        }
        }
        }
        }
    }//GEN-LAST:event_btnentregarActionPerformed

    private void btnconsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconsultarActionPerformed
        // TODO add your handling code here:
        
         pkgModelo.clsDAOentregar obj;
        obj=new pkgModelo.clsDAOentregar();
        
        String de=JOptionPane.showInputDialog("INGRESE NUMERO CODIGO");
        //txtId.setText(de); este metodo tambien sirve par buscar por cedula
         obj.setId(de);
         if (de.isEmpty()){
        JOptionPane.showMessageDialog(null, "INGRESE CODIGO", "ERROR", JOptionPane.ERROR_MESSAGE);
            
        }else{
         java.util.ArrayList resu = new java.util.ArrayList();
         resu=obj.consultar();
         if (resu.size() == 0){
            JOptionPane.showMessageDialog(null, "NO EXISTE");
         }else{
             
            resibonombre.setText(resu.get(0).toString());
             resibonombrelibro.setText(resu.get(2).toString());
            txtresiboReferencia.setText(resu.get(1).toString());
            txtresiboId.setText(de);
        }
        
         }
    }//GEN-LAST:event_btnconsultarActionPerformed

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMenu().setVisible(true);
            }
        });
        this.dispose();
    }//GEN-LAST:event_btnsalirActionPerformed

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
        // TODO add your handling code here:
        
        
        
        
        pkgModelo.clsDAOentregar obj;
        obj=new pkgModelo.clsDAOentregar();
        int fila=tableinfo.getSelectedRow();
        if (fila != -1){
            String codigo=tableinfo.getValueAt(fila, 0).toString();
            obj.setId(codigo);
            obj.borrar();
            listar();
        }
        else{

            JOptionPane.showMessageDialog(null, "SELECCIONE UNA COLUMNA PARA BORRAR", "ERROR", JOptionPane.ERROR_MESSAGE);
            
     }
    }//GEN-LAST:event_btneliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfrdevoluciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfrdevoluciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfrdevoluciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfrdevoluciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfrdevoluciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnconsultar;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btnentregar;
    private javax.swing.JButton btnsalir;
    private javax.swing.JLabel hora;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNombrelibro;
    private javax.swing.JLabel lblfecha;
    private javax.swing.JLabel lblhora;
    private javax.swing.JLabel lblinfo;
    private javax.swing.JLabel lblreferencia;
    public static javax.swing.JTextField resibonombre;
    public static javax.swing.JTextField resibonombrelibro;
    private javax.swing.JTable tableinfo;
    public static javax.swing.JTextField txtresiboId;
    public static javax.swing.JTextField txtresiboReferencia;
    // End of variables declaration//GEN-END:variables
}
